export const arrayProductos = [
  {
    id: 1,
    nombre: "Iphone 15 PRO (128-256GB) Titanio Gris",
    descuento: 2700000,
    precio: 199999,
    stock: 8,
    descripcion:
      "El iPhone 15 Pro (128-256GB) Titanio Gris es la última versión del icónico smartphone de Apple. Con una elegante carcasa de titanio en color gris, ofrece capacidades de almacenamiento de 128GB o 256GB para satisfacer tus necesidades digitales. Equipado con tecnología de vanguardia, una potente cámara, y un rendimiento excepcional, el iPhone 15 Pro redefine la experiencia móvil de alta gama.",
    img: "https://static2.o9.de/resource/blob/1504566/5c3b5b8ebb2d87e3933025c6e4cf870e/png/apple-iphone-15-pro-max-natur-gallerybild-1-data.webp",
  },
  {
    id: 2,
    nombre: "Notebook LENOVO Ideapad 114 Gray Intel Dual Core",
    descuento: 599999,
    precio: 369999,
    stock: 4,
    descripcion:
      "La Notebook LENOVO Ideapad 114 Gray Intel Dual Core es una computadora portátil compacta y eficiente, ideal para tareas diarias. Equipada con un procesador Intel Dual Core, ofrece un rendimiento confiable para navegación web, correo electrónico, y tareas de oficina. Su diseño en color gris le otorga un aspecto moderno y elegante, perfecto para usuarios que buscan funcionalidad y estilo en un dispositivo portátil.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfBndBAuOb-sKrwD-2FQwyUmkb2czFxI_KD5fN05Z-MA&s",
  },
  {
    id: 3,
    nombre: "Tablet SAMSUNG Galaxy Tab S6 Lite 64/4gb 10,4 Wifi",
    descuento: 849999,
    precio: 699999,
    stock: 0,
    descripcion:
      "La Tablet SAMSUNG Galaxy Tab S6 Lite ofrece una experiencia versátil y portátil con su pantalla de 10,4 pulgadas. Con 64GB de almacenamiento y 4GB de RAM, proporciona un rendimiento fluido para navegar por internet, disfrutar de contenido multimedia y ejecutar aplicaciones. Con conectividad Wi-Fi, es ideal para quienes buscan una tablet compacta y potente para el entretenimiento y la productividad en cualquier lugar.",
    img: "https://images.samsung.com/is/image/samsung/ar-galaxy-tab-s6-lite-p610-sm-p610nzauaro-frontgray-282037279?$650_519_PNG$",
  },
  {
    id: 4,
    nombre: "Reloj Smartwatch Samsung Galaxy Watch 5 44mm ",
    descuento: 63799,
    precio: 43999,
    stock: 1,
    descripcion:
      "El Reloj Smartwatch Samsung Galaxy Watch 5 de 44mm combina estilo y funcionalidad en un dispositivo de alta tecnología. Con una pantalla nítida y vibrante, ofrece seguimiento de actividad física, notificaciones inteligentes y una variedad de funciones útiles. Su diseño elegante y resistente lo convierte en el compañero perfecto para un estilo de vida activo y conectado.",
    img: "https://www.venex.com.ar/products_images/1681733785_smart-4.png",
  },
  {
    id: 5,
    nombre: 'Smart TV 55" Samsung 4K AU7000',
    descuento: 622999,
    precio: 520199,
    stock: 9,
    descripcion:
      "La Smart TV Samsung AU7000 de 55'' ofrece una experiencia visual impresionante con su pantalla 4K de alta resolución. Equipada con tecnología inteligente, permite acceder a una amplia gama de aplicaciones de entretenimiento y servicios de transmisión. Con un diseño elegante y delgado, esta televisión proporciona una experiencia inmersiva para disfrutar de películas, programas de televisión y contenido en línea con una calidad excepcional. ",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzOSehTThEvfHd3ijdaa_ib-TalPVxwV_8vru_vHWmdQ&s",
  },
  {
    id: 6,
    nombre: "Pc Gamer Completa Amd Ryzen 7 5700g 16g Nvme",
    descuento: 928239,
    precio: 888239,
    stock: 11,
    descripcion:
      "La PC Gamer completa con procesador AMD Ryzen 7 5700G y 16GB de RAM NVMe ofrece un rendimiento potente y fluido para juegos y multitarea intensiva. Con gráficos integrados de alta calidad, proporciona una experiencia visual impresionante sin necesidad de una tarjeta gráfica dedicada. Equipada con almacenamiento NVMe ultrarrápido, ofrece tiempos de carga rápidos y capacidad de respuesta. Esta PC está lista para brindar una experiencia de juego inmersiva y sin interrupciones para satisfacer las demandas de los jugadores más exigentes.",
    img: "https://http2.mlstatic.com/D_NQ_NP_634957-MLA72460118206_102023-O.webp",
  },
  {
    id: 7,
    nombre: "Playstation 5 825gb God Of War Ragnarok Bundle",
    descuento: 1429999,
    precio: 999999,
    stock: 6,
    descripcion:
      "La PlayStation 5 825GB God of War Ragnarok Bundle ofrece una experiencia de juego de última generación junto con el esperado título God of War Ragnarok. Con su potente hardware y almacenamiento de 825GB, la consola proporciona gráficos impresionantes y tiempos de carga ultrarrápidos. El bundle incluye el juego God of War Ragnarok, llevando a los jugadores a una emocionante aventura en la mitología nórdica. Esta combinación ofrece horas de entretenimiento épico y una experiencia inmersiva para los aficionados a los videojuegos.",
    img: "https://http2.mlstatic.com/D_NQ_NP_661625-MLU72835349237_112023-O.webp",
  },
  {
    id: 8,
    nombre: "Sony Home Theater 5.1 de Canales Con Parlantes",
    descuento: 1899999,
    precio: 1199999,
    stock: 15,
    descripcion:
      "El Sony Home Theater 5.1 de Canales con Parlantes proporciona una experiencia de audio envolvente y de alta calidad para disfrutar de películas, música y juegos en el hogar. Con un sistema de sonido de cinco canales y un subwoofer incluido, ofrece un audio potente y claro que llena la habitación. Equipado con tecnologías avanzadas de procesamiento de audio de Sony, este sistema garantiza una reproducción precisa y envolvente del sonido, brindando una experiencia de entretenimiento inmersiva y emocionante para toda la familia.",
    img: "https://http2.mlstatic.com/D_NQ_NP_700741-MLU72851416358_112023-O.webp",
  },
  {
    id: 9,
    nombre: "Heladera Freezer Superior Samsung No Frost 382lt",
    descuento: 1364999,
    precio: 1149999,
    stock: 2,
    descripcion:
      "La Heladera Freezer Superior Samsung No Frost de 382 litros ofrece una solución espaciosa y conveniente para el almacenamiento de alimentos. Con tecnología No Frost, evita la formación de hielo en el congelador, lo que significa menos mantenimiento y una mejor conservación de los alimentos. Su diseño con freezer en la parte superior facilita el acceso a los productos congelados, mientras que el amplio compartimento de la heladera proporciona organización y capacidad para los alimentos frescos. Con un diseño moderno y eficiente, esta heladera es ideal para hogares que buscan comodidad y durabilidad en sus electrodomésticos.",
    img: "https://http2.mlstatic.com/D_NQ_NP_934114-MLA50722767788_072022-O.webp",
  },
  {
    id: 10,
    nombre: "Lavarropas Inverter Samsung Carga Frontal 9.5kg",
    descuento: 1049999,
    precio: 944999,
    stock: 1,
    descripcion: "El Lavarropas Inverter Samsung de Carga Frontal con capacidad de 9.5kg ofrece una solución eficiente y confiable para el lavado de ropa. Con tecnología Inverter, garantiza un funcionamiento más silencioso y un menor consumo de energía, lo que resulta en un ahorro a largo plazo. Su diseño de carga frontal facilita la carga y descarga de la ropa, mientras que su amplia capacidad permite lavar grandes cargas en cada ciclo. Equipado con múltiples programas de lavado y funciones adicionales, este lavarropas ofrece versatilidad y comodidad para adaptarse a diferentes tipos de prendas y necesidades de lavado. Es una opción ideal para hogares que buscan eficiencia y rendimiento en su electrodoméstico de lavado.",
    img: "https://www.rodo.com.ar/media/catalog/product/cache/855090a5c67e45b26c9e0d345e7592dc/3/5/353721_lavarropas_samsung_4.jpg",
  },
  {
    id: 11,
    nombre: "Aire acondicionado Philco split frío/calor 2560 frigorías",
    descuento: 722499,
    precio: 577799,
    stock: 0,
    descripcion: "El aire acondicionado Philco Split frío/calor de 2560 frigorías es un sistema versátil que proporciona tanto enfriamiento como calefacción para espacios medianos a grandes. Con diseño Split, ofrece eficiencia energética y confort, con características modernas como control remoto y temporizadores programables. Ideal para mantener un ambiente interior confortable durante todo el año.",
    img: "https://philco.com.ar/media/catalog/product/cache/c8f6a96bef9e9f64cd4973587df2520f/a/i/aire_acondicionado_split_fr_ocalor_2560w_negro_philco.jpg",
  },
  {
    id: 12,
    nombre: "Horno de mesa eléctrico Ultracomb 45L negro/rojo",
    descuento: 198799,
    precio: 153577,
    stock: 1,
    descripcion: "El horno de mesa eléctrico Ultracomb de 45 litros en color negro/rojo es un electrodoméstico compacto y versátil diseñado para cocinar una variedad de alimentos. Con capacidad para 45 litros, es ideal para hogares pequeños o como complemento a la cocina principal. Su diseño de mesa permite colocarlo fácilmente en cualquier superficie plana. Con funciones de horneado, asado y tostado, ofrece opciones culinarias variadas. Además, su estética en negro/rojo le da un toque moderno a la cocina.",
    img: "https://http2.mlstatic.com/D_NQ_NP_711042-MLU72558581086_112023-O.webp",
  },
  {
    id: 13,
    nombre: "Tostadora Eléctrica Atma To8020i 700w 7 Niveles",
    descuento: 47729,
    precio: 30499,
    stock: 4,
    descripcion: "La Tostadora Eléctrica Atma TO8020i es un electrodoméstico diseñado para tostar pan de manera rápida y eficiente. Con una potencia de 700W, ofrece un rendimiento adecuado para un uso doméstico estándar. Este modelo cuenta con 7 niveles de tostado que permiten ajustar el grado de dorado del pan según las preferencias del usuario, desde un tostado ligero hasta uno más crujiente y oscuro.",
    img: "https://http2.mlstatic.com/D_NQ_NP_740243-MLU73980704810_012024-O.webp",
  },
  {
    id: 14,
    nombre: "Cafetera Nespresso Essenza C30 Con Aeroccino",
    descuento: 289999,
    precio: 254599,
    stock: 0,
    descripcion: "La Cafetera Nespresso Essenza C30 con Aeroccino es una máquina de café compacta y elegante que ofrece la conveniencia de preparar café de alta calidad en casa con solo presionar un botón. Esta cafetera utiliza cápsulas Nespresso para garantizar una experiencia consistente y deliciosa en cada taza. El modelo Essenza C30 viene equipado con el Aeroccino, un accesorio que permite espumar la leche automáticamente para preparar una variedad de bebidas como capuchinos y lattes. Con su diseño intuitivo y tamaño compacto, es ideal para espacios reducidos en la cocina.",
    img: "https://images.fravega.com/f300/b3a707f361fd16e86041a0500d3e2260.jpg.webp",
  },
  {
    id: 15,
    nombre: "Microondas Samsung Grill Cerámico Triple 23l Sl",
    descuento: 321999,
    precio: 275999,
    stock: 8,
    descripcion: "El Microondas Samsung Grill Cerámico Triple de 23 litros (modelo SL) es un electrodoméstico de cocina versátil y eficiente que combina la tecnología de microondas con una función de grill. Con su capacidad de 23 litros, es ideal para hogares pequeños o medianos. Este microondas utiliza un revestimiento interior de cerámica triple, que no solo facilita la limpieza, sino que también proporciona una distribución más uniforme del calor, lo que resulta en alimentos cocinados de manera más uniforme y con menos riesgo de quemarse.",
    img: "https://www.rodo.com.ar/media/catalog/product/cache/855090a5c67e45b26c9e0d345e7592dc/3/1/315656_samsung_microondas_2.jpg",
  },
  {
    id: 16,
    nombre: "Licuadora Smartlife 1,5 litros",
    descuento: 89999,
    precio: 69999,
    stock: 7,
    descripcion: "La Licuadora Smartlife de 1,5 litros es un electrodoméstico diseñado para la preparación de batidos, jugos y otras bebidas con ingredientes frescos. Con una capacidad de 1,5 litros, es ideal para uso doméstico y puede satisfacer las necesidades de una familia pequeña o mediana. Este modelo de licuadora suele estar equipado con un motor potente que permite triturar fácilmente frutas, verduras y otros ingredientes, proporcionando resultados suaves y consistentes. Además, generalmente ofrece múltiples velocidades y funciones preprogramadas para adaptarse a diferentes tipos de alimentos y preferencias de preparación.",
    img: "https://smartlifear.vtexassets.com/arquivos/ids/155404-800-auto?v=638127554587230000&width=800&height=auto&aspect=true",
  },
];
